"""add repo meta, commits, issue first response, contributor stats

Revision ID: a2c1528214e2
Revises: cd004c38ac16
Create Date: 2026-08-25 20:24:03.669519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2c1528214e2'
down_revision: Union[str, None] = 'cd004c38ac16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repo_id', sa.Integer(), nullable=False),
    sa.Column('sha', sa.String(), nullable=False),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('authored_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repo_id', 'sha', name='uq_commit_repo_sha')
    )
    op.create_index('ix_commit_repo_authored', 'commits', ['repo_id', 'authored_at'], unique=False)
    op.add_column('contributors', sa.Column('prs_merged', sa.Integer(), nullable=True))
    op.add_column('contributors', sa.Column('reviews', sa.Integer(), nullable=True))
    op.add_column('contributors', sa.Column('last_active_at', sa.DateTime(), nullable=True))
    op.add_column('issues', sa.Column('first_response_at', sa.DateTime(), nullable=True))
    op.create_index('ix_issue_repo_created', 'issues', ['repo_id', 'created_at'], unique=False)
    op.create_index('ix_pr_repo_closed', 'pull_requests', ['repo_id', 'closed_at'], unique=False)
    op.add_column('repos', sa.Column('stars', sa.Integer(), nullable=True))
    op.add_column('repos', sa.Column('forks', sa.Integer(), nullable=True))
    op.add_column('repos', sa.Column('language', sa.String(), nullable=True))
    op.add_column('repos', sa.Column('license', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repos', 'license')
    op.drop_column('repos', 'language')
    op.drop_column('repos', 'forks')
    op.drop_column('repos', 'stars')
    op.drop_index('ix_pr_repo_closed', table_name='pull_requests')
    op.drop_index('ix_issue_repo_created', table_name='issues')
    op.drop_column('issues', 'first_response_at')
    op.drop_column('contributors', 'last_active_at')
    op.drop_column('contributors', 'reviews')
    op.drop_column('contributors', 'prs_merged')
    op.drop_index('ix_commit_repo_authored', table_name='commits')
    op.drop_table('commits')
    # ### end Alembic commands ###
