"""add tracked_repos join table

Revision ID: af86509c98d4
Revises: 79bf05f4e584
Create Date: 2026-08-30 14:28:44.274326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af86509c98d4'
down_revision: Union[str, None] = '79bf05f4e584'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracked_repos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('repo_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'repo_id', name='uq_tracked_repo_user_repo')
    )
    op.create_index('ix_tracked_repos_user', 'tracked_repos', ['user_id'], unique=False)
    # ### end Alembic commands ###

    # Backfill: every repo that existed before this migration was visible to
    # every user (there was no ownership at all yet). Landing this with an
    # empty tracked_repos table would silently empty every existing user's
    # dashboard — not a bug fix from their side of it, just repos vanishing.
    # Link everyone who already has an account to everything that already
    # existed, so today's dashboards look the same the moment this ships;
    # the join table only starts actually restricting anything for repos
    # and users added after this point.
    op.execute(
        """
        INSERT INTO tracked_repos (user_id, repo_id, created_at)
        SELECT users.id, repos.id, now()
        FROM users CROSS JOIN repos
        """
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tracked_repos_user', table_name='tracked_repos')
    op.drop_table('tracked_repos')
    # ### end Alembic commands ###
